Add bookmark system for lf
Move down

Fix bug in lf bookmark system, but not finish.

Refractor lf bookmark system

Fix fzf bug in lf bookmark system

diff --git a/.config/lf/lfrc b/.config/lf/lfrc
--- a/.config/lf/lfrc
+++ b/.config/lf/lfrc
@@ -16,8 +16,11 @@ set cleaner ~/.config/lf/lf_kitty_clean
 set sixel true
 set scrolloff 1
 set mouse
+set period 1
+set info size
+set dircounts
 
-map ` mark-load
+map p :paste; clear
 
 
 # ============
@@ -159,6 +162,70 @@ cmd select-dirs &{{
 
     lf -remote "send $id :unselect; toggle $(get_dirs)"
 }}
+cmd bookmark_create %{{
+    mkdir -p "$LF_BOOKMARK_PATH"
+    printf "Mark current path to (string): "
+    read ans
+    if [ -z "$ans" ]; then
+        lf -remote "send $id reload"
+        exit 0
+    fi
+    for f in "$LF_BOOKMARK_PATH"/*; do
+        if [ ! -f "$f" ]; then
+            continue
+        fi
+        target_path="$(cat "$f")"
+        if [ ! -d "$target_path" ] || [ "$PWD" = "$target_path" ]; then
+            rm "$f"
+        fi
+    done
+    echo "$PWD" > "${LF_BOOKMARK_PATH}/${ans}"
+    lf -remote "send $id reload"
+}}
+cmd bookmark_jump ${{
+    mkdir -p "$LF_BOOKMARK_PATH"
+    target_mark="$(ls "$LF_BOOKMARK_PATH" | fzf || exit 0)"
+    if [ -z "$target_mark" ]; then
+        exit 0
+    fi
+    target_path="$(cat "${LF_BOOKMARK_PATH}/${target_mark}" 2> /dev/null)"
+    if [ ! -d "$target_path" ]; then
+        rm "${LF_BOOKMARK_PATH}/${target_mark}"
+        printf 'Path not found, Removed from bookmarks.'
+        exit 0
+    fi
+    lf -remote "send $id cd \"$target_path\""
+}}
+cmd bookmark_remove ${{
+    [ ! -d "$LF_BOOKMARK_PATH" ] && exit 0
+    for f in "$LF_BOOKMARK_PATH"/*; do
+        if [ ! -f "$f" ]; then
+            continue
+        fi
+        if [ "$PWD" = "$(cat "$f")" ]; then
+            rm "$f"
+        fi
+    done
+}}
+cmd bookmark_remove_not_exist ${{
+    [ ! -d "$LF_BOOKMARK_PATH" ] && exit 0
+    for f in "$LF_BOOKMARK_PATH"/*; do
+        if [ ! -f "$f" ]; then
+            continue
+        fi
+        if [ ! -d "$(cat "$f")" ]; then
+            rm "$f"
+        fi
+    done
+}}
+cmd bookmark_remove_all ${{
+    rm -rf "$LF_BOOKMARK_PATH" 2> /dev/null
+}}
+map m bookmark_create
+map ` bookmark_jump
+map <a-m> bookmark_remove
+map <a-'> bookmark_remove_not_exist
+map <a-"> bookmark_remove_all
 
 
 # ===============
@@ -210,8 +277,15 @@ map O $mimeopen --ask $f
 # text files and a file opener for the rest.
 cmd open &{{
     case $(file --mime-type -Lb $f) in
-        text/*) lf -remote "send $id \$$EDITOR \$fx";;
-        *) for f in $fx; do $OPENER $f > /dev/null 2> /dev/null & done;;
+        text/*)
+            lf -remote "send $id \$$EDITOR \$fx"
+            ;;
+        application/pdf)
+            for f in $fx; do zathura $f > /dev/null 2> /dev/null & done
+            ;;
+        *)
+            for f in $fx; do $OPENER $f > /dev/null 2> /dev/null & done
+            ;;
     esac
 }}
 
@@ -246,14 +320,15 @@ cmd open &{{
 # (xkcd link: https://xkcd.com/1168/)
 cmd extract ${{
     set -f
-    case $f in
-        *.tar.bz|*.tar.bz2|*.tbz|*.tbz2) tar xjvf $f;;
-        *.tar.gz|*.tgz) tar xzvf $f;;
-        *.tar.xz|*.txz) tar xJvf $f;;
-        *.zip) unzip $f;;
-        *.rar) unrar x $f;;
-        *.7z) 7z x $f;;
-    esac
+    # case $f in
+    #     *.tar.bz|*.tar.bz2|*.tbz|*.tbz2) tar xjvf $f;;
+    #     *.tar.gz|*.tgz) tar xzvf $f;;
+    #     *.tar.xz|*.txz) tar xJvf $f;;
+    #     *.zip) unzip $f;;
+    #     *.rar) unrar x $f;;
+    #     *.7z) 7z x $f;;
+    # esac
+    atool -x $f
 }}
 
 # compress current file or selected files with tar and gunzip
